jobs/urls.py
from django.conf.urls import patterns, url

from jobs import views

urlpatterns = patterns('',
	url(r'^jobs/$', views.JobIndexView.as_view(), name='job_index'),
	url(r'^jobs/(?P<pk>\d+)/$', views.JobDetailView.as_view(), name='job_detail'),
	url(r'^jobs/(?P<pk>\d+)/edit/$', views.JobUpdate.as_view(), name='job_update'),
	url(r'^clients/$', views.ClientIndexView.as_view(), name='client_index'),
	url(r'^clients/(?P<pk>\d+)/$', views.ClientDetail.as_view(), name='client_detail'),
	url(r'^clients/(?P<pk>\d+)/edit/$', views.ClientUpdate.as_view(), name='client_update'),
	url(r'^clients/new/$', views.ClientCreateForm.as_view(), name='client_create'),
	)

kitchenstudio/urls.py
from django.conf.urls import patterns, include, url
from django.conf import settings

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'kitchenstudio.views.home', name='home'),
    # url(r'^kitchenstudio/', include('kitchenstudio.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
    (r'^static/(.*)$', 'django.views.static.serve', { 'document_root': settings.STATIC_ROOT }),
    url(r'^', include('jobs.urls', namespace="jobs")),
    
)

if not settings.DEBUG:
    urlpatterns += patterns('',
        (r'^static/(.*)$', 'django.views.static.serve', { 'document_root': settings.STATIC_ROOT }),
    )

jobs/models.py
from django.db import models
from django.core.urlresolvers import reverse
import datetime
from django.utils import timezone
from django.db.models import Max, Sum
import operator


class Address(models.Model):
	STREET = 'ST'
	ROAD = 'RD'
	AVENUE = 'AV'
	CRESCENT = 'CR'
	BOULEVARD = 'BL'
	STREET_TYPE_CHOICES = (
		(STREET, 'Street'),
		(ROAD, 'Road'),
		(AVENUE, 'Avenue'),
		(CRESCENT, 'Crescent'),
		(BOULEVARD, 'Boulevard'),
	)
	number = models.CharField(max_length=10)
	street = models.CharField(max_length=50)
	street_type = models.CharField(max_length=2, choices=STREET_TYPE_CHOICES)
	suburb = models.CharField(max_length=30,blank=True)
	city = models.CharField(max_length=30)

	def __unicode__(self):
		if (self.suburb != ""):
			address_string = u"%s %s %s, %s, %s" % (self.number, self.street, 
				self.get_street_type_display(), self.suburb, self.city)
		else:
			address_string = u"%s %s %s, %s" % (self.number, self.street,
				self.get_street_type_display(), self.city)
		return address_string


class Client(models.Model):
	first_name = models.CharField(max_length=30)
	last_name = models.CharField(max_length=30)
	email = models.EmailField(blank=True, null=True)
	address = models.ForeignKey(Address)

	def get_absolute_url(self):
		return reverse('jobs:client_detail', kwargs={'pk': self.pk})

	def __unicode__(self):
		return u"%s %s" % (self.first_name, self.last_name)


class Phone(models.Model):
	HOME = 'HM'
	WORK = 'WK'
	FAX = 'FX'
	MOBILE = 'MB'
	PHONE_TYPE_CHOICES = (
		(HOME, 'Home'),
		(WORK, 'Work'),
		(FAX, 'Fax'),
		(MOBILE, 'Mobile'),
	)
	client = models.ForeignKey(Client)
	area_code = models.CharField(max_length=3, blank=True)
	number = models.CharField(max_length=15)
	phone_type = models.CharField(max_length=2, choices=PHONE_TYPE_CHOICES)

	def __unicode__(self):
		phone_string = u"%s : (%s) %s" % (self.get_phone_type_display(), 
			self.area_code, self.number)
		return phone_string


class Job(models.Model):
	client = models.ForeignKey(Client)
	address = models.ForeignKey(Address)
	budget = models.DecimalField(blank=True, null=True, max_digits=8, 
		decimal_places=2)
	final_price = models.DecimalField(blank=True, null=True, max_digits=8, 
		decimal_places=2)
	consultation_date = models.DateField()

	def __unicode__(self):
		job_string = u"%s | %s | Consultation on %s" % (self.client, self.address, 
			self.consultation_date)
		return job_string

	def latest_event(self):
		return self.jobevent_set.latest('date')

	def get_final_price(self):
		self.final_price = self.jobevent_set.aggregate(
			total_price=Sum('price'))['total_price']
		return self.final_price
		

class JobEvent(models.Model):
	CONSULTATION = 'CL'
	PRICED = 'PR'
	PENDING = 'PD'
	UNSOLD = 'US'
	SOLD = 'SD'
	ADDITIONAL_SALE = 'AS'
	DESIGNED = 'DS'
	INSTALL_DATE = 'ID'
	INSTALL_START = 'IS'
	INSTALL_FIN = 'IF'
	JOB_STATUS_CHOICES = (
		(CONSULTATION, 'Consultation'),
		(PRICED, 'Priced'),
		(PENDING, 'Pending'),
		(UNSOLD, 'Unsold'),
		(SOLD, 'Sold'),
		(ADDITIONAL_SALE, 'Additional Sale'),
		(DESIGNED, 'Designed'),
		(INSTALL_DATE, 'Installation Date'),
		(INSTALL_START, 'Installation Started'),
		(INSTALL_FIN, 'Installation Finished'),
	)	
	job_status = models.CharField(max_length=2, choices=JOB_STATUS_CHOICES)
	job = models.ForeignKey(Job)
	date = models.DateField()
	price = models.DecimalField(max_digits=8, decimal_places=2,
		help_text="Change in price.", blank=True, null=True)
	comment = models.TextField(blank=True, null=True)

	def __unicode__(self):
		jobevent_string = u"%s on %s" % (self.get_job_status_display(), self.date)
		return jobevent_string

# class SaleEvent(models.Model):
# 	job = models.ForeignKey(Job)
# 	price = models.DecimalField(max_digits=6, decimal_places=2)
# 	date = models.DateField()
# 	comment = models.TextField(blank=True, null=True)
		
# def getLCD(job):
# 	return job.latest_consultation_date()

# jobs.sort(key=getLCD)

jobs/forms.py
from django.forms.models import modelformset_factory, inlineformset_factory
from django.forms.formsets import formset_factory
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit
import floppyforms as forms
from jobs.models import Client, Job, JobEvent, Address


class JobUpdateForm(forms.ModelForm):
	class Meta:
		model = Job

	def __init__(self, *args, **kwargs):
		super(JobUpdateForm, self).__init__(*args, **kwargs)
		self.helper = FormHelper()
		self.helper.add_input(Submit('submit', 'Submit'))


class JobEventForm(forms.ModelForm):
	class Meta:
		model = JobEvent


class ClientUpdateForm(forms.ModelForm):
	class Meta:
		exclude = ('address')
		model = Client

	def __init__(self, *args, **kwargs):
		super(ClientUpdateForm, self).__init__(*args, **kwargs)
		self.helper = FormHelper()
		self.helper.add_input(Submit('submit', 'Submit'))

class ClientCreateForm(forms.ModelForm):
	class Meta:
		model = Client
		template_name = 'jobs/client_form.html'

class AddressCreateForm(forms.ModelForm):
	class Meta:
		model = Address
			
			
ClientFormSet = inlineformset_factory(Address, Client)

jobs/views.py
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, get_object_or_404
from django.views.generic import ListView, DetailView 
from django.views.generic.edit import UpdateView, CreateView, DeleteView

from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit
from django import forms

from jobs.models import Job, JobEvent, Client
from jobs.forms import * #ClientUpdateForm, ClientFormSet

# def index(request):
#   jobs_list = Job.objects.all()
#   context = {'jobs_list': jobs_list}
#   return render(request, 'jobs/index.html', context)

# def detail(request, job_id):
#   return HttpResponse("You're looking at job %s." % job_id)

def getObjectList(objects):
    objectList = list(objects)
    objectList.sort(key=getLCD)
    return objectList


class JobIndexView(ListView):
    template_name = 'jobs/job_index.html'
    context_object_name = 'job_list'
    queryset = Job.objects.order_by('-consultation_date')


class JobDetailView(DetailView):
    model = Job
    template_name = 'jobs/job_detail.html'


class ClientIndexView(ListView):
    template_name = 'jobs/client_index.html'
    context_object_name = 'client_list'
    queryset = Client.objects.order_by('last_name')

class ClientCreateView(CreateView):
    model = Client
    form_class = ClientCreateForm

class ClientDetail(DetailView):
    model = Client
    template_name = 'jobs/client_detail.html'


class ClientUpdate(UpdateView):
    model = Client

    form_class = ClientFormSet

class JobUpdate(UpdateView):
    model = Job


def new_client(request):
    # if request.method == 'POST':
    client_form = ClientCreateForm(request.POST)
    address_form = AddressCreateForm(request.POST)
    print "post"
    if client_form.is_valid() and address_form.is_valid():
        print "valid"
        a = address_form.save()
        c = client_form.save(commit=false)
        c.a = a
        c.save()
        return HttpResponseRedirect('/jobs/')
    # else:
    #     return HttpResponseRedirect('/jobs/')

jobs/templates/jobs/client_detail.html
{% extends "jobs/job_base.html" %}

{% block title %}Client: {{ client }}{% endblock %}

{% block content %}
	<h1>{{ client }}</h1>

	<p>{{ client.first_name }}</p>
	<p>{{ client.last_name }}</p>

	<p>{{ client.email }}
	<p>{{ client.address }} </p>

	<ul>
		{% for phone in client.phone_set.all %}
			<li>{{ phone }}</li>
		{% endfor %}
	</ul>
	<p><a href="{% url 'jobs:client_update' client.id %}">Edit the Client details.</a></p>
	<p><a href="{% url 'jobs:client_index' %}">Back to Client list.</a></p>
{% endblock %}

jobs/templates/jobs/client_form.html
{% extends "jobs/job_base.html" %}

{% block title %}Client: {{ client }}{% endblock %}

{% block content %}
	<!-- <form action="" method="post">{% csrf_token %}
		{{ form.as_p }}
		<input type="submit" value="Submit" />
	</form> -->
	{% load crispy_forms_tags %}
	{% crispy form %}
{% endblock %}

jobs/templates/jobs/client_index.html
{% extends "jobs/job_base.html" %}

{% block title %}Clients{% endblock %}

{% block content %}
	{% if client_list %}
		<ul>
			{% for client in client_list %}
				<li><a href="{% url 'jobs:client_detail' client.id %}">{{ client }}
				</a> | {{ client.address }}</li>
			{% endfor %}
		</ul>
	{% else %}
		<p>There are no clients.</p>
	{% endif %}

	<a href="{% url 'jobs:client_create' %}">New Client</a>
{% endblock %}

jobs/templates/jobs/detail.html
<h1>{{ job.client }} | {{ job.address }}</h1>

<p>Budget is ${{ job.budget }}.</p>
<p>Estimated cost is ${{ job.estimated_cost }}.</p>

<ul>
	{% for event in job.jobevent_set.all %}
		<li>
			<p>{{ event }}: {{ event.date }}</p> 
			<p>{{ event.comment }}</p>
		</li>
	{% endfor %}
</ul>

<p><a href="{% url 'jobs:index' %}">Back to Jobs list.</a></p>

jobs/templates/jobs/index.html
<html>
	<head>
		<title>Kitchen Studio Jobs</title>
	</head>
	<body>
		{% if jobs_list %}
			<ul>
				{% for job in jobs_list %}

					<li><a href="{% url 'jobs:detail' job.id %}">{{ job.client}} | {{ job.address }} | {{ job.latest_consultation_date }}</a></li>
				{% endfor %}
			</ul>
		{% else %}
			<p>No jobs are started</p>
		{% endif %}
	</body>
</html>

jobs/templates/jobs/job_base.html
<!DOCTYPE HTML>

<html lang="en">

<head>
	<meta charset="utf-8">
	<meta content="width=device-width, initial-scale=1.0" name="viewport">

	<title>Kitchen Studio {% block title %}{% endblock %}</title>

	{% load staticfiles %}
	<link rel="stylesheet" type="text/css" href="{% static 'jobs/main.css' %}">
	<!-- <link rel="stylesheet" href="{% static 'jobs/pure-min.css' %}" />
	<link rel="stylesheet" href="{% static 'jobs/style.css' %}" /> -->
	
</head>

<body>
	<div id="layout" class="pure-g-r">
		
		<div id="menu" class="pure-u">
			<div class="pure-menu pure-menu-open">
				{% block sidebar %}
				<a class="pure-menu-heading" href="{% url 'jobs:job_index' %}">Kitchen Studio</a>
				<ul>
					{% load admin_urls %}
					<li><a href="{% url 'admin:index' %}">Admin</a></li>
					<li><a href="{% url 'jobs:job_index' %}">Jobs</a></li>
					<li><a href="{% url 'jobs:client_index' %}">Clients</a></li>
				</ul>
				{% endblock %}
			</div>
		</div>

		<div id="main" class="pure-u">
			{% block content %}{% endblock %}
		</div>
		
	</div>
</body>
</html>

jobs/templates/jobs/job_detail.html
{% extends "jobs/job_base.html" %}

{% block title %}Job: {{ job }}{% endblock %}

{% block content %}
	<h1><a href="{% url 'jobs:client_detail' job.client.id %}">{{ job.client }}</a> | {{ job.address }}</h1>

	<p>Budget is ${{ job.budget }}.</p>
	<p>Final Price is ${{ job.get_final_price }}.</p>
	<p>Consultation on {{ job.consultation_date }}.</p>
	<ul>
		{% for event in job.jobevent_set.all %}
			<li>
				<p>{{ event }}: {{ event.date }}</p> 
				<p>{{ event.comment }}</p>
			</li>
		{% endfor %}
	</ul>

	<p><a href="{% url 'jobs:job_update' job.id %}">Edit the Job details.</a></p>
	<p><a href="{% url 'jobs:job_index' %}">Back to Jobs list.</a></p>
{% endblock %}

jobs/templates/jobs/job_form.html
{% extends "jobs/job_base.html" %}

{% block title %}Job: {{ job }}{% endblock %}

{% block content %}
	<!-- <form action="" method="post">{% csrf_token %}
		{{ form.as_p }}
		<input type="submit" value="Submit" />
	</form> -->
	{% load crispy_forms_tags %}
	{% crispy form %}
{% endblock %}

jobs/templates/jobs/job_index.html
{% extends "jobs/job_base.html" %}

{% block title %}Jobs{% endblock %}

{% block content %}
	{% if job_list %}
		<ul>
			{% for job in job_list %}
				<li><a href="{% url 'jobs:job_detail' job.id %}">{{ job.client}} | {{ job.address }} | Consultation on {{ job.consultation_date }}</a>
					<button type="button" value="Edit" 
					onclick="location.href='{% url 'jobs:job_update' job.id %}';">Edit</button></li>
			{% endfor %}
		</ul>
	{% else %}
		<p>No jobs are started.</p>
	{% endif %}
{% endblock %}